baseURL = "https://ziv.github.io/airborne/"
locale = "en-us"
title = "Airborne"
theme = "re-terminal"

[services]
    [services.googleAnalytics]
        id = 'G-0GMMREP8RD'

[params]
    themeColor = "pink"
    contentTypeName = "posts"

[params.twitter]
    creator = "zivdev"

[markup.goldmark.renderer]
    unsafe = true

[author]
    name = "Ziv Perry"
    email = "ziv.perry@gmail.com"

[languages]
    [languages.en.params]
        languageName = "English"
        title = "AIRBORNE"
        subtitle = "Development blog"

    [languages.en.params.logo]
        logoText = "AIRBORNE"
        logoHomeLink = "/airborne/"

    [languages.en.menu]
        [[languages.en.menu.main]]
            identifier = "about"
            name = "About"
            url = "/about"
        [[languages.en.menu.main]]
            identifier = "repo"
            name = "Repository"
            url = "https://github.com/ziv/airborne"
