baseURL = "https://ziv.github.io/airborne/"
locale = "en-us"
title = "Airborne"
theme = "re-terminal"

[markup.goldmark.renderer]
    unsafe = true

[author]
    name = "Ziv Perry"
    email = "ziv.perry@gmail.com"

[languages]
    [languages.en.params]
        languageName = "English"
            title = "AIRBORNE"
            subtitle = "Development blog"


        [languages.en.params.logo]
            logoText = "AIRBORNE"
            logoHomeLink = "/airborne/"