/**
 * @file AircraftStructs.h
 * @brief Core data structures shared across the aircraft simulation pipeline.
 *
 * Defines PilotControls (input), PhysicsForces (computed forces), Orientation
 * (quaternion-based rotation), LandingZoneInfo, and the central AircraftState
 * that is passed through controls → physics → transformation → camera each frame.
 */
#pragma once
#include "raylib.h"
#include "raymath.h"
#include "../primitives/Constants.h"
#include "../primitives/Types.h"

/// @brief Raw pilot input values produced by AircraftControls each frame.
struct PilotControls {
    float pitch;      ///< Pitch input (positive = nose down, negative = nose up), scaled by dt.
    float yaw;        ///< Yaw input (positive = left, negative = right), scaled by dt.
    float roll;       ///< Roll input (positive = right, negative = left), scaled by dt.
    float throttle;   ///< Throttle setting [0.0 – 1.0], >1.0 = afterburner (max 1.2).
    bool brakes;      ///< True when wheel brakes (ground) or air brakes (flying) are engaged.
    bool gear;        ///< True when landing gear is deployed.
};

/// @brief Computed aerodynamic forces and velocity produced by AircraftPhysics.
struct PhysicsForces {
    Newton thrust;           ///< Forward thrust force from the engine.
    Newton drag;             ///< Aerodynamic drag opposing motion.
    Newton lift;             ///< Upward lift generated by the wings.
    MeterPerSecond speed;    ///< Scalar speed (magnitude of velocity).
    Vector3 velocity;        ///< 3D velocity vector in world space.
};

/// @brief Quaternion-based aircraft orientation with pre-computed basis vectors.
struct Orientation {
    Quaternion rotation;  ///< Master orientation quaternion.
    Vector3 forward;      ///< Unit vector pointing along the aircraft nose.
    Vector3 up;           ///< Unit vector pointing above the aircraft canopy.
    Vector3 right;        ///< Unit vector pointing along the right wing.
};

/// Describes the landing zone the aircraft is currently over (if any).
/// Updated each frame by GameData before physics runs.
struct LandingZoneInfo {
    bool active = false; // true when over a valid landing strip
    bool isCarrier = false; // carrier deck vs ground airstrip
    float surfaceHeight = 0.0f; // deck height (150m carrier, 0m ground)
};

/**
 * @brief Central mutable state of the player's aircraft, passed through
 *        every simulation subsystem each frame.
 *
 * Uses a large-world coordinate trick: `position` stays near the origin while
 * `mapOffset` accumulates shifts whenever coordinates exceed SHIFT_THRESHOLD,
 * preventing floating-point precision loss over large distances.
 */
struct AircraftState {
    /// Accumulated world-space shift applied to keep `position` near the origin.
    Vector3 worldOffset = {0.0f, 0.0f, 0.0f};

    /// When any axis of `position` exceeds this, coordinates are re-centered.
    const float SHIFT_THRESHOLD = 5000.0f;

    PilotControls controls = {
        0.0f,
        0.0f,
        0.0f,
        0.0f,
        true,
        true
    };
    PhysicsForces forces = {
        0.0_ntn,
        0.0_ntn,
        0.0_ntn,
        0.0_mps,
        {0.0f, 0.0f, 0.0f}
    };
    Orientation orientation = {
        {0.0f, 0.0f, 0.0f, 1.0f},
        GamePhysics::WorldForward,
        GamePhysics::WorldUp,
        GamePhysics::WorldRight
    };
    Vector3 position = {
        0.0f,
        0.0f,
        0.0f
    };
    Vector2 mapOffset = {0.0f, 0.0f};   ///< Accumulated XZ offset for the large-world shift.

    float groundHeight = 0;              ///< Terrain height (meters) directly below the aircraft.
    bool flying = false;                 ///< True when airborne (above effectiveFloorHeight + 1 m).
    bool crashed = false;                ///< True after a crash — freezes the simulation.
    float fuel = 3500;                   ///< Remaining fuel in kilograms.

    /// The minimum Y the aircraft can be at (surface + wheel clearance).
    /// Set each frame by GameData before physics runs.
    float effectiveFloorHeight = 0.0f;

    /// Landing zone info for the current frame (set by GameData).
    LandingZoneInfo landingZone;

    /// @brief Returns the current position of the aircraft in world coordinates (i.e. with world offset applied).
    [[nodiscard]] Vector3 pos() const {
        return position - (Vector3){mapOffset.x, 0.0f, mapOffset.y};
    }

    /// @brief Converts a position relative to the aircraft into world coordinates (i.e. with world offset applied).
    // [[nodiscard]] Vector3 location(const Vector3 &relativePosition) const {
    // return relativePosition + worldOffset;
    // }

    /// @brief Checks if a position is too far from the aircraft to be drawn (i.e. outside the draw distance).
    // we draw only items in 50,000m radius todo take value from config
    [[nodiscard]] bool tooFar2Draw(const Vector3 &them) const {
        return Vector3Distance(pos(), them) > 150000;
    }
};
